ALTER TABLE `creature_text` ADD `BroadcastTextID` MEDIUMINT(6) DEFAULT 0 NOT NULL;

ALTER TABLE `gossip_menu_option` ADD `OptionBroadcastTextID` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `option_text`;
ALTER TABLE `gossip_menu_option` ADD `BoxBroadcastTextID` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `box_text`;

ALTER TABLE `npc_text` ADD `BroadcastTextID0` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `text0_1`;
ALTER TABLE `npc_text` ADD `BroadcastTextID1` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `text1_1`;
ALTER TABLE `npc_text` ADD `BroadcastTextID2` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `text2_1`;
ALTER TABLE `npc_text` ADD `BroadcastTextID3` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `text3_1`;
ALTER TABLE `npc_text` ADD `BroadcastTextID4` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `text4_1`;
ALTER TABLE `npc_text` ADD `BroadcastTextID5` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `text5_1`;
ALTER TABLE `npc_text` ADD `BroadcastTextID6` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `text6_1`;
ALTER TABLE `npc_text` ADD `BroadcastTextID7` MEDIUMINT(6) DEFAULT 0 NOT NULL AFTER `text7_1`;
